//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreaturDatos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatos
    {
        public int Id { get; set; }
        public string FacturaProveedor { get; set; }
        public string ObservacionesAdministracion { get; set; }
        public string NumFacturaCreatur { get; set; }
        public string ObservacionIngreso { get; set; }
        public string FacturaEfectiva { get; set; }
        public string Agente { get; set; }
        public string FechaCreacion { get; set; }
        public string Refacturacion { get; set; }
        public string HK { get; set; }
        public string GK { get; set; }
        public string Huesped { get; set; }
        public string Empresa { get; set; }
        public string Hotel { get; set; }
        public string CiudadUbicacionHotel { get; set; }
        public string Confirmacion { get; set; }
        public Nullable<System.DateTime> FechaCheckIn { get; set; }
        public Nullable<System.DateTime> FechaCheckOut { get; set; }
        public Nullable<int> NumeroNoches { get; set; }
        public Nullable<double> TarifaBaseConImpIncluidos { get; set; }
        public Nullable<double> TotalConImpIncluidos { get; set; }
        public Nullable<double> TotalTarifaBaseHotel { get; set; }
        public string ISH { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<double> PorcenGananSobreTotalImpuestosInclud { get; set; }
        public double ImporteGanancia { get; set; }
        public string ServiciosAdicionales { get; set; }
        public Nullable<double> CargoServicio { get; set; }
        public Nullable<double> ImporteServicioAdicional { get; set; }
        public Nullable<double> PorcenGananciaSobreServAdicional { get; set; }
        public Nullable<double> ImporteGananciaSobreServicioAdicional { get; set; }
        public Nullable<double> TotalFacHospedaje { get; set; }
        public string FormaPago { get; set; }
        public string TipoTarifa { get; set; }
        public string NumRechazadosDeTarjetas { get; set; }
        public string ReservaEfectiva { get; set; }
        public string ImporteCobrarHtl { get; set; }
        public string FOPFinal { get; set; }
        public string ObservacionDireccion { get; set; }
    }
}
