<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MostrarUsuarios.aspx.cs" Inherits="CreaturDatos.MostrarUsuarios" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="viewport" content="initial-scale=1, maximum-scale=1"/>
<link  rel="stylesheet" type="text/css" href="css/Normalize.css"/>
<link  rel="stylesheet" type="text/css" href="css/EstiloMostrarUsuario.css"/>
<script src="Scripts/jquery-1.3.2.min.js" type="text/javascript"></script>
    <title>Mostrar usuarios</title>

<%--    <script lang="javascript" type="text/javascript">
        $(document).ready(function () {
            //agregar una nueva columna con todo el texto 
            //contenido en las columnas de la grilla 
            // contains de Jquery es CaseSentive, por eso a minúscula
            $(".filtrar tr:has(td)").each(function () {
                var t = $(this).text().toLowerCase();
                $("<td class='indexColumn'></td>")
                .hide().text(t).appendTo(this);
            });
            //Agregar el comportamiento al texto (se selecciona por el ID) 
            $("#tbBuscar").keyup(function () {
                var s = $(this).val().toLowerCase().split(" ");
                $(".filtrar tr:hidden").show();
                $.each(s, function () {
                    $(".filtrar tr:visible .indexColumn:not(:contains('"
                    + this + "'))").parent().hide();
                });
            });
        });
     </script>--%>

</head>
<body>



    <div id="headerMosUsuario">
    <header>
        <h1>Mostrar Usuarios</h1>
    </header>
    </div>


    <div>
    <form  runat="server">
        
            <asp:ImageButton ID="imgBtnHome" runat="server" ImageUrl="~/img/homebtn.png" style="position:absolute; top:8px; width:60px; height:60px; left:1080px;" OnClick="imgBtnHome_Click"/>
            <asp:Label ID="lblHome" runat="server" Text="Inicio" style="position:absolute; top:70px; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size:12px; color:white; left:1097px;" ></asp:Label>

        <div id="contFiltros">
           
                <asp:Label ID="lblBuscar" runat="server" Text="Buscar correo:" style="font-family:'Segoe UI'; font-size:20px;
                color:#0094ff; position:absolute; top:20px; left:335px; width:144px;"></asp:Label>
                <asp:Label ID="lblNombre" runat="server" Text="Buscar nombre:" style="font-family:'Segoe UI'; font-size:20px;
                color:#0094ff; position:absolute; top:74px; left:325px; width:144px;"></asp:Label>
                <asp:ImageButton ID="btnBuscarImage" CssClass="botonRedondo" style="height:80px; width:80px;
                margin-left:30px; position:absolute; top:22px; left:626px;"  runat="server" Text="" ImageUrl="~/img/buscarImg.png" />
                <asp:ImageButton ID="imgBtnExcel" CssClass="botonRedondo" style="height:80px; width:80px;
                margin-left:30px; position:absolute; top:22px; left:742px;"  runat="server" Text="" ImageUrl="~/img/exportar.png" OnClick="imgBtnExcel_Click"/>
                <asp:TextBox ID="tbBuscar" runat="server" style="position:absolute; top:24px; left:478px; width: 140px;" OnTextChanged="tbBuscar_TextChanged"></asp:TextBox>
                <asp:TextBox ID="tbBuscarNombre" runat="server" style="position:absolute; top:78px; left:478px; width: 140px;"></asp:TextBox>
           
          </div>

        <div id="gvUsers">
            <strong>
            <asp:GridView ID="gdUsuario" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" Width="1200px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" AllowPaging="True" PageSize="30" Height="270px" style="position:absolute; left:70px;">
                <Columns>
                    <asp:BoundField DataField="Nombre" HeaderText="Nombre" SortExpression="Nombre" ItemStyle-HorizontalAlign="Center"/>
                    <asp:BoundField DataField="Correo" HeaderText="Correo" SortExpression="Correo" ItemStyle-HorizontalAlign="Center"/>
                    <asp:BoundField DataField="TipoUsuario" HeaderText="Tipo de usuario" SortExpression="TipoUsuario" ItemStyle-HorizontalAlign="Center"/>
                    <asp:BoundField DataField="Contra" HeaderText="Contra" SortExpression="Contra" ItemStyle-HorizontalAlign="Center"/>
                </Columns>
                <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                <RowStyle BackColor="White" ForeColor="#003399" />
                <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                <SortedAscendingCellStyle BackColor="#EDF6F6" />
                <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                <SortedDescendingCellStyle BackColor="#D6DFDF" />
                <SortedDescendingHeaderStyle BackColor="#002876" />
            </asp:GridView>
            </strong>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DBCreaturHotelConnectionString3 %>" 
                SelectCommand="SELECT * FROM [tblUsuarios] WHERE (([Nombre] LIKE '%' + @nombre + '%') AND ([Correo] LIKE '%' + @correo + '%'))" CancelSelectOnNullParameter="False"
                UpdateCommand =" UPDATE [tblUsuarios] SET [Nombre]=@nombre, [Correo]=@correo, [TipoUsuario]=@tipoUsuario, [Contra]=@contra WHERE [Id]=@id"
                DeleteCommand="DELETE FROM [tblUsuarios] WHERE [Id]=@id">
                <SelectParameters>
                     <asp:ControlParameter ControlID="tbBuscarNombre" Name="nombre" PropertyName="Text"  Type="String" ConvertEmptyStringToNull="False"/>
                     <asp:ControlParameter ControlID="tbBuscar" Name="correo" PropertyName="Text" Type="String" ConvertEmptyStringToNull="False"/>
                 </SelectParameters>

            </asp:SqlDataSource>
        </div>
     </form>
     </div>

</body>
</html>
